- modules/signatures/windows_utilities.py
https://www.sentinelone.com/blog/malware-living-off-land-with-certutil/
> Add in signature for certutil lolbin

- lib/cuckoo/core/database.py
that oneline for was breaking sometime as it was using sample var as return var
> fix sample lookup

- modules/signatures/cape_extracted.py
> Add  sig to highlight CAPE extracted content

- modules/signatures/windows_utilities.py
From testing file for the ATT&CK technique
> Add sig for modifying accessibility binaries

- modules/signatures/powershell_command.py
> Add & modify powershell sigs

- modules/signatures/stack_pivot.py
Split out some of this to be more informative. There is still a FP issue in IE I have noticed being generated on public CAPE needing remediated at some point.
Still stack pivots are rare in modern exploits the last few years though once the pyrebox stuff is over that will help a lot :D
> Updated stack pivot sig

- modules/signatures/bypass_uac.py
Added sig for eventvwr bypass technique
> Add signature for UAC bypass techniques

- modules/signatures/windows_utilities.py
> Add signature for csc.exe use

- lib/cuckoo/common/abstracts.py
- lib/cuckoo/common/objects.py
- lib/cuckoo/core/database.py
- lib/cuckoo/core/scheduler.py
- modules/processing/CAPE.py
- modules/processing/static.py
- modules/processing/strings.py
- modules/processing/targetinfo.py
- web/templates/analysis/overview/index.html
- web/templates/analysis/static/index.html
- web/templates/submission/index.html
* Allow static extraction,
* Code cleanup
* remove support for yara 1.77(too damn old, compile from source)
> Static extraction

- cuckoo.py
- docs/book/src/installation/host/configuration.rst
- docs/book/src/installation/host/index.rst
- docs/book/src/installation/host/installation.rst
- docs/book/src/installation/host/requirements.rst
- docs/book/src/usage/utilities.rst
- lib/cuckoo/core/startup.py
> Revert "remove everything related to comminity.py and basic doc which suggest…"

- conf/multi.conf
- lib/cuckoo/common/abstracts.py
- modules/machinery/multi.py
- web/submission/views.py
multimachinery is taken from https://github.com/cuckoosandbox/cuckoo/pull/2840/files
and done for cape :)
> multimachinery

- modules/signatures/office_macro_suspicious.py
> Add in sig for mmbot malicious macro predictions

- modules/signatures/packer_anomaly.py
> Add signature for packer unknown section name

- modules/signatures/static_pe_anomaly.py
Based on this and PDB hunting concepts https://www.fireeye.com/blog/threat-research/2019/08/definitive-dossier-of-devilish-debug-details-part-one-pdb-paths-malware.html. There is some useful Yara rules for this which is useful at the end in .pdf format
patchwork:
Emotet:
Ryuk
> Add in PDB signature

- modules/signatures/script_downloader.py
> Add additional network APIs into script downloader

- data/yara/binaries/shellcodes.yar
From William Ballenthin and his excellent shellcode talk https://www.youtube.com/watch?v=9pyR_C4LpFM
> Update shellcode Yara rules with fireeye sigs

- modules/reporting/mongodb.py
This PR fixes a long standing bug in the MongoDB reporting module code.
MongoDB needs JSON documents to only contain valid UTF-8 strings.
When the analysis report/object contains binary data (either due to faulty malware config extractors, or simply due to API calls with binary data as arguments) the reporting module will fail when the pymongo/bson package raises an InvalidStringData exception.
This change traverses the analysis report data, validates the strings in the report, and if they are not UTF-8 decodable (e.g. binary junk, memory buffers, etc.), it converts them to a UTF-8 encoded representation that yields the same binary data when decoded.
Note: This also has not been fixed in Cuckoo v2.0:
https://github.com/cuckoosandbox/cuckoo/issues/2686 …
> Fixes an issue that causes MongoDB inserts to fail occasionally

- modules/signatures/powershell_command.py
> Add sig for curtain results

- modules/signatures/ransomware_message.py
Add in another technique of basically dropping a text or HTML file throughout the filesystem which is used in ransomware
Eris Ransomware
> Add additional ransomware message file detection technique

- modules/signatures/disables_run_command.py
Reference: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc938270(v=technet.10)?redirectedfrom=MSDN
Sample: 37be8fc43943a34f08e0a70be87b45272efc68620b650f4c59cd68d2155fcc36
> Add signature for disabling run command

- modules/signatures/browser_proxy.py
> Fix PDF exclusion in proxy sig
